### ISSUE TITLE
Many errors in production logs

### ISSUE THREAD

**Issue by ijunaid8989** [EdgeCommander/edge-commander#112]
Go through each of them and fix them.
```
05:08:06.301 [error] Task #PID<0.577.0> started from #PID<0.576.0> terminating
2018-01-31T05:08:06.301671+00:00 app[web.1]: ** (BadMapError) expected a map, got: nil
2018-01-31T05:08:06.301672+00:00 app[web.1]:     (stdlib) :maps.remove("reason", nil)
2018-01-31T05:08:06.301674+00:00 app[web.1]:     (edge_commander) lib/edge_commander/monitors/portable.ex:67: EdgeCommander.Portable.update_nvr_status/3
2018-01-31T05:08:06.301676+00:00 app[web.1]:     (elixir) lib/enum.ex:675: Enum."-each/2-lists^foreach/1-0-"/2
2018-01-31T05:08:06.301678+00:00 app[web.1]:     (elixir) lib/enum.ex:675: Enum.each/2
2018-01-31T05:08:06.301680+00:00 app[web.1]:     (quantum) lib/quantum/executor.ex:98: Quantum.Executor.execute_task/1
2018-01-31T05:08:06.301681+00:00 app[web.1]:     (elixir) lib/task/supervised.ex:85: Task.Supervised.do_apply/2
2018-01-31T05:08:06.301683+00:00 app[web.1]:     (elixir) lib/task/supervised.ex:36: Task.Supervised.reply/5
2018-01-31T05:08:06.301685+00:00 app[web.1]:     (stdlib) proc_lib.erl:247: :proc_lib.init_p_do_apply/3
2018-01-31T05:08:06.301687+00:00 app[web.1]: Function: #Function<6.79063667/0 in Quantum.Executor.run/3>
2018-01-31T05:08:06.301689+00:00 app[web.1]:     Args: []
2018-01-31T05:08:18.959582+00:00 app[web.1]: 05:08:18.959 request_id=33dc4f54-77a2-4464-bebc-a7291c15d74f [info] GET /delivery_receipt
2018-01-31T05:08:18.963225+00:00 app[web.1]: 05:08:18.963 [error] #PID<0.582.0> running EdgeCommanderWeb.Endpoint terminated
2018-01-31T05:08:18.961736+00:00 app[web.1]: 05:08:18.961 request_id=33dc4f54-77a2-4464-bebc-a7291c15d74f [info] Sent 500 in 2ms
2018-01-31T05:08:18.963227+00:00 app[web.1]: Server: app.edgecommander.com:80 (http)
2018-01-31T05:08:18.963229+00:00 app[web.1]: Request: GET /delivery_receipt?msisdn=353867514314&to=353872705838&network-code=27202&messageId=0D0000007780398E&price=0.05850000&status=accepted&scts=1801301203&err-code=1&client-ref=SMe672cfdbf11d067f&message-timestamp=2018-01-30+12%3A03%3A37
2018-01-31T05:08:18.963230+00:00 app[web.1]: ** (exit) an exception was raised:
2018-01-31T05:08:18.963231+00:00 app[web.1]:     ** (FunctionClauseError) no function clause matching in EdgeCommander.Nexmo.SimMessages.changeset/2
2018-01-31T05:08:18.963233+00:00 app[web.1]:         (edge_commander) lib/edge_commander/nexmo/sim_messages.ex:20: EdgeCommander.Nexmo.SimMessages.changeset(nil, %{status: "accepted"})
2018-01-31T05:08:18.963236+00:00 app[web.1]:         (edge_commander) lib/edge_commander_web/controllers/sims_controller.ex:1: EdgeCommanderWeb.SimsController.action/2
2018-01-31T05:08:18.963234+00:00 app[web.1]:         (edge_commander) lib/edge_commander_web/controllers/sims_controller.ex:161: EdgeCommanderWeb.SimsController.delivery_receipt/2
2018-01-31T05:08:18.963237+00:00 app[web.1]:         (edge_commander) lib/edge_commander_web/controllers/sims_controller.ex:1: EdgeCommanderWeb.SimsController.phoenix_controller_pipeline/2
2018-01-31T05:08:18.963238+00:00 app[web.1]:         (edge_commander) lib/edge_commander_web/endpoint.ex:1: EdgeCommanderWeb.Endpoint.instrument/4
2018-01-31T05:08:18.963240+00:00 app[web.1]:         (phoenix) lib/phoenix/router.ex:278: Phoenix.Router.__call__/1
2018-01-31T05:08:18.963241+00:00 app[web.1]:         (edge_commander) lib/edge_commander_web/endpoint.ex:1: EdgeCommanderWeb.Endpoint.plug_builder_call/2
2018-01-31T05:08:18.967190+00:00 app[web.1]: 05:08:18.966 request_id=28944cf1-7582-479f-beb7-63bc76821bb6 [info] GET /delivery_receipt
2018-01-31T05:08:18.963243+00:00 app[web.1]:         (edge_commander) lib/edge_commander_web/endpoint.ex:1: EdgeCommanderWeb.Endpoint.call/2
2018-01-31T05:08:18.968943+00:00 app[web.1]: 05:08:18.968 request_id=28944cf1-7582-479f-beb7-63bc76821bb6 [info] Sent 500 in 1ms
2018-01-31T05:08:18.970444+00:00 app[web.1]: 05:08:18.970 [error] #PID<0.583.0> running EdgeCommanderWeb.Endpoint terminated
2018-01-31T05:08:18.970449+00:00 app[web.1]: Request: GET /delivery_receipt?msisdn=353867514314&to=353872705838&network-code=27202&messageId=0D0000007780398E&price=0.05850000&status=delivered&scts=1801301203&err-code=0&client-ref=SMe672cfdbf11d067f&message-timestamp=2018-01-30+12%3A03%3A39
2018-01-31T05:08:18.970446+00:00 app[web.1]: Server: app.edgecommander.com:80 (http)
2018-01-31T05:08:18.970451+00:00 app[web.1]: ** (exit) an exception was raised:
2018-01-31T05:08:18.970453+00:00 app[web.1]:     ** (FunctionClauseError) no function clause matching in EdgeCommander.Nexmo.SimMessages.changeset/2
2018-01-31T05:08:18.970457+00:00 app[web.1]:         (edge_commander) lib/edge_commander_web/controllers/sims_controller.ex:161: EdgeCommanderWeb.SimsController.delivery_receipt/2
2018-01-31T05:08:18.970459+00:00 app[web.1]:         (edge_commander) lib/edge_commander_web/controllers/sims_controller.ex:1: EdgeCommanderWeb.SimsController.action/2
2018-01-31T05:08:18.970455+00:00 app[web.1]:         (edge_commander) lib/edge_commander/nexmo/sim_messages.ex:20: EdgeCommander.Nexmo.SimMessages.changeset(nil, %{status: "delivered"})
2018-01-31T05:08:18.970461+00:00 app[web.1]:         (edge_commander) lib/edge_commander_web/controllers/sims_controller.ex:1: EdgeCommanderWeb.SimsController.phoenix_controller_pipeline/2
2018-01-31T05:08:18.970463+00:00 app[web.1]:         (edge_commander) lib/edge_commander_web/endpoint.ex:1: EdgeCommanderWeb.Endpoint.instrument/4
2018-01-31T05:08:18.970465+00:00 app[web.1]:         (phoenix) lib/phoenix/router.ex:278: Phoenix.Router.__call__/1
2018-01-31T05:08:18.970466+00:00 app[web.1]:         (edge_commander) lib/edge_commander_web/endpoint.ex:1: EdgeCommanderWeb.Endpoint.plug_builder_call/2
2018-01-31T05:08:18.970468+00:00 app[web.1]:         (edge_commander) lib/edge_commander_web/endpoint.ex:1: EdgeCommanderWeb.Endpoint.call/2
2018-01-31T05:08:18.963431+00:00 heroku[router]: at=info method=GET path="/delivery_receipt?msisdn=353867514314&to=353872705838&network-code=27202&messageId=0D0000007780398E&price=0.05850000&status=accept
```

**Comment by Ali7862** [comment]
it's done.
